name: BUILD_FFMPEG_BY_MANUAL(BTBN)

on:
  workflow_dispatch:
    inputs:
      bash_branch:
        description: "指定BtbN分支"
        required: true
        default: "master"
        type: choice
        options:
          - "master"
      bash_commit_id:
        description: "指定BtbN使用commit id版本"
        required: true
        default: "HEAD~0"
        type: string
      ffmpeg_branch:
        description: "指定ffmpeg分支"
        required: true
        default: "master"
        type: choice
        options:
          - "master"
          - "8.0"
      svt_av1_commit_id:
        description: "指定svt-av1使用commit id版本"
        required: true
        default: "v3.1.2"
        type: string
      svt_av1_custom_version:
        description: "use svt-av1 custom version"
        default: "auto"
        type: choice
        options:
          - "default"
          - "auto"
          - "custom"
      release_archives:
        description: "enable release archives"
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}

jobs:
  pre:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    outputs:
      default_commit_id: HEAD~0
      default_branch: ${{ steps.set_global_params.outputs.default_branch }}
      mingw_w64_commit_id: ${{ steps.set_global_params_mingw_w64.outputs.mingw_w64_commit_id }}
      mingw_w64_commit_id_static: "c4ae0f47b9adf0b6b91dcc906f5b1fbfe342bb42"
      svt_av1_commit_id: ${{ steps.set_global_params_svt_av1.outputs.svt_av1_commit_id }}
      svt_av1_commit_id_static: "ce61a98aec134f48b5c0251661a32301b8c801e5"
    steps:
      - name: set_global_params
        id: set_global_params
        run: |
          echo "default_branch=main" >> "$GITHUB_OUTPUT"

      - name: set_global_params (mingw_w64)
        id: set_global_params_mingw_w64
        run: |
          branch=master
          commit_id=$(git ls-remote https://github.com/mingw-w64/mingw-w64.git refs/heads/$branch | cut -f1)
          echo "mingw_w64_commit_id=$commit_id" >> "$GITHUB_OUTPUT"

      - name: set_global_params (svt_av1)
        id: set_global_params_svt_av1
        run: |
          branch=master
          commit_id=$(git ls-remote https://gitlab.com/AOMediaCodec/SVT-AV1.git refs/heads/$branch | cut -f1)
          echo "svt_av1_commit_id=$commit_id" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: [pre]
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        os: [win64, linux64, linuxarm64]
    steps:
      - name: Free Disk-Space
        run: df -h && sudo apt-get clean && docker system prune -a -f && sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc && df -h
      #- name: Free Disk Space (Ubuntu)
      #  uses: jlumbroso/free-disk-space@main
      #  with:
      #    tool-cache: false
      #    android: true
      #    dotnet: true
      #    haskell: true
      #    large-packages: true
      #    docker-images: false
      #    swap-storage: true

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v10.2.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: git curl subversion

      - name: set branch params[master]
        if: ${{ inputs.ffmpeg_branch == 'master' }}
        run: |
          echo ffmpeg_branch_fullname=${{ inputs.ffmpeg_branch }} >> $GITHUB_ENV

      - name: set branch params[release]
        if: ${{ inputs.ffmpeg_branch != 'master' }}
        run: |
          echo ffmpeg_branch_fullname="release/${{ inputs.ffmpeg_branch }}" >> $GITHUB_ENV

      - name: Get FFmpeg commit
        run: |
          mkdir -p ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          git clone --depth=1 -b ${{ env.ffmpeg_branch_fullname }} https://github.com/FFmpeg/FFmpeg.git
          cd ${{ github.workspace }}/build/FFmpeg
          echo "ffmpeg_sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: git clone bash
        run: |
          mkdir -p ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          git clone -b ${{ inputs.bash_branch }} https://github.com/BtbN/FFmpeg-Builds.git
          cd ${{ github.workspace }}/build/FFmpeg-Builds
          git checkout --force --quiet ${{ inputs.bash_commit_id }}

      - name: add master branch addin
        run: |
          cp -rf ${{ github.workspace }}/ext/addins/. ${{ github.workspace }}/build/FFmpeg-Builds/addins/

      - name: fix base remote repo
        run: |
          sed -i 's/GITHUB_REPOSITORY/GITHUB_REPOSITORY_LOCAL/g' ${{ github.workspace }}/build/FFmpeg-Builds/util/vars.sh
          sed -i 's/REGISTRY_OVERRIDE/REGISTRY_OVERRIDE_LOCAL/g' ${{ github.workspace }}/build/FFmpeg-Builds/util/vars.sh
          cat ${{ github.workspace }}/build/FFmpeg-Builds/util/vars.sh
      
      - name: (custom_auto) gnulib
        run: |
          sed -i 's#"https://git.savannah.gnu.org/git/gnulib.git"#"https://github.com/coreutils/gnulib.git"#g' ${{ github.workspace }}/build/FFmpeg-Builds/scripts.d/20-libiconv.sh
          cat ${{ github.workspace }}/build/FFmpeg-Builds/scripts.d/20-libiconv.sh

      - name: (custom) av1-svt
        if: ${{ inputs.svt_av1_custom_version == 'custom' }}
        run: |
          sed -i 's/SCRIPT_COMMIT="[0-9a-f]\+"/SCRIPT_COMMIT="${{ inputs.svt_av1_commit_id }}"/g' ${{ github.workspace }}/build/FFmpeg-Builds/scripts.d/50-svtav1.sh
          cat ${{ github.workspace }}/build/FFmpeg-Builds/scripts.d/50-svtav1.sh

      - name: (custom_auto) av1-svt
        if: ${{ inputs.svt_av1_custom_version == 'auto' }}
        run: |
          sed -i 's/SCRIPT_COMMIT="[0-9a-f]\+"/SCRIPT_COMMIT="${{ needs.pre.outputs.svt_av1_commit_id_static }}"/g' ${{ github.workspace }}/build/FFmpeg-Builds/scripts.d/50-svtav1.sh
          cat ${{ github.workspace }}/build/FFmpeg-Builds/scripts.d/50-svtav1.sh

      - name: (custom_auto) mingw_w64
        run: |
          sed -i 's#"https://git.code.sf.net/p/mingw-w64/mingw-w64.git"#"https://github.com/mingw-w64/mingw-w64.git"#g' ${{ github.workspace }}/build/FFmpeg-Builds/scripts.d/10-mingw.sh
          sed -i 's/SCRIPT_COMMIT="[0-9a-f]\+"/SCRIPT_COMMIT="${{ needs.pre.outputs.mingw_w64_commit_id_static }}"/g' ${{ github.workspace }}/build/FFmpeg-Builds/scripts.d/10-mingw.sh
          cat ${{ github.workspace }}/build/FFmpeg-Builds/scripts.d/10-mingw.sh

      - name: docker prune all
        run: |
          docker builder prune --all

      - name: set build env params
        run: |
          echo "QUICKBUILD=1" >> "$GITHUB_ENV"

      - name: build base image
        run: |
          cd ${{ github.workspace }}/build/FFmpeg-Builds/
          ./makeimage.sh ${{ matrix.os }} nonfree ${{ inputs.ffmpeg_branch }}

      - name: build ffmpeg
        run: |
          cd ${{ github.workspace }}/build/FFmpeg-Builds/
          ./build.sh ${{ matrix.os }} nonfree ${{ inputs.ffmpeg_branch }}

      - name: show build result files
        run: |
          ls -R ${{ github.workspace }}/build/FFmpeg-Builds/artifacts

      - name: 7-Zip FFmpeg binaries
        run: |
          7z a -mx9 ${{ github.workspace }}/temp/ffmpeg-bin-${{ matrix.os }}-${{ env.ffmpeg_sha_short }}-nonfree.7z ${{ github.workspace }}/build/FFmpeg-Builds/artifacts/*

      - name: show zip files
        run: |
          ls -R ${{ github.workspace }}/temp

      - name: Upload FFmpeg binaries
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-bin-${{ matrix.os }}-${{ env.ffmpeg_sha_short }}-nonfree
          compression-level: 9
          path: |
            ${{ github.workspace }}/temp/*
          if-no-files-found: error

  release:
    needs: [pre, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      #- name: Free Disk-Space
      #  run: df -h && sudo apt-get clean && docker system prune -a -f && sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc && df -h
      #- name: Free Disk Space (Ubuntu)
      #  uses: jlumbroso/free-disk-space@main
      #  with:
      #    tool-cache: false
      #    android: true
      #    dotnet: true
      #    haskell: true
      #    large-packages: true
      #    docker-images: false
      #    swap-storage: true

      - name: Checkout
        uses: actions/checkout@v5

      - name: Download FFmpeg archives
        uses: actions/download-artifact@v5
        with:
          pattern: ffmpeg-bin-*
          merge-multiple: true
          path: ${{ github.workspace }}/archives

      - name: show zip files
        run: |
          ls -R ${{ github.workspace }}/archives

      - name: Get current date time
        run: |
          echo "current_date_time=$(TZ=Asia/Shanghai date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_ENV"

      - name: Release FFmpeg archives
        uses: softprops/action-gh-release@v2
        if: ${{ inputs.release_archives }}
        with:
          tag_name: "V2-${{ env.current_date_time }}"
          name: "V2-${{ env.current_date_time }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          body: "FFmpeg nonfree build result (BtbN/FFmpeg-Builds)."
          files: |
            ${{ github.workspace }}/archives/**
